---
- hosts: home-lab-ios
  gather_facts: no
  tasks:
    
    - name: setup interface
      ios_l3_interface:
        name: "{{ item['name'] }}"
        #enabled: "{{ item['enabled'] }}"
        #state: "{{ item['state'] }}"
        ipv4: "{{ item['ipv4'] }}"
      loop: "{{ interfaces }}"

    - name: bgp conf
      template:
        src: "templates/{{ ansible_network_os }}_bgp.j2"
        dest: "configs/{{ inventory_hostname }}.config"      
    
    - name: load conf
      ios_config:
        src: "configs/{{ inventory_hostname }}.config"
      register: updates

    - name: debug updates
      debug:
        msg: "{{ updates.updates }}"

    - name: show bgp output
      ios_command:
        commands:  
          - show ip bgp summary
      register: output

    - name: display output
      debug:
        var: output
